CREATE TABLE USERBALADEIRO (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(100),
 email VARCHAR(100),
 idade INT,
 points INT,
 checkIn BOOLEAN,
 balada VARCHAR(100),
 estilo VARCHAR(100)
);

